# Generated by Django 5.1.1 on 2024-11-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='arquivo_adicional',
            field=models.FileField(blank=True, null=True, upload_to='demandas/arquivos/', verbose_name='Arquivo Adicional'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='categoria',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='nome_solicitante',
            field=models.CharField(default='Desconhecido', max_length=255, verbose_name='Nome do Solicitante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demanda',
            name='taxa_urgencia',
            field=models.BooleanField(default=False, verbose_name='Taxa de Urgência Necessária'),
        ),
    ]
