# Generated by Django 5.1.1 on 2024-11-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_demanda_arquivo_adicional_demanda_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='visivel',
            field=models.BooleanField(default=True, verbose_name='Visível'),
        ),
    ]
