# Generated by Django 5.1.1 on 2024-12-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_membro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
