# Generated by Django 5.1.1 on 2024-12-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_membro_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
