# Generated by Django 5.1.1 on 2025-01-22 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_demanda_data_demanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='data_demanda',
            field=models.DateField(default=datetime.date.today, verbose_name='Data da Demanda'),
        ),
    ]
