# Generated by Django 4.2 on 2025-01-30 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_demanda_data_demanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='data_demanda',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data da Demanda'),
        ),
    ]
